# Generated by Django 2.2.24 on 2021-09-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='boilpoint',
        ),
        migrations.AddField(
            model_name='chemical',
            name='boilingpoint',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='b.p.(K)'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='meltingpoint',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='m.p.(K)'),
        ),
    ]
